### ISSUE TITLE
使断开连接信息提示更简洁

### ISSUE THREAD

**Issue by Bliod-Cook** [SerendipityR-2022/EndMinecraftPlusV2#10]
![image](https://user-images.githubusercontent.com/108209631/202888555-e89d0189-f940-4546-9a76-3b895502293d.png)
在连接的时候被踢出或者因为其他原因断开连接 显示的信息会非常长

**Comment by SerendipityR-2022** [comment]
部分消息不能被反序列化，未来可能会修复。
