### ISSUE TITLE
端口错误

### ISSUE THREAD

**Issue by MCyudix** [SerendipityR-2022/EndMinecraftPlusV2#11]
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:90021
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:80891
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:90911
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:80801
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:99963
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:80123
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:80801
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:90914
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:90911
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:90911
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:81181
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:80891
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:80123
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:80894
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:99912
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:80891
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:88812
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:80891
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:99921
[Internal Error] 发生错误: java.lang.IllegalArgumentException: port out of range:80188

**Comment by SerendipityR-2022** [comment]
无法确定问题所在

**Comment by Bliod-Cook** [comment]
我也有这个问题 用自带的下载器下载 .txt的代理的时候会有这个问题

**Comment by SerendipityR-2022** [comment]
> 我也有这个问题 用自带的下载器下载 .txt的代理的时候会有这个问题

检查你的代理地址端口，有效值应为1-65535。
