### ISSUE TITLE
错误: 找不到或无法加载主类 C:\Users\Administrator\Desktop\EndMinecraftPlusV2\EndMinecraftPlusV2.jar

### ISSUE THREAD

**Issue by bailijerry** [SerendipityR-2022/EndMinecraftPlusV2#16]
"C:\Program Files\Java\jre1.8.0_341\bin\java.exe" -Xmx1G "C:\Users\Administrator\Desktop\EndMinecraftPlusV2\EndMinecraftPlusV2.jar"
pause

**Comment by SerendipityR-2022** [comment]
遗漏了 `-jar` 参数。
