### ISSUE TITLE
支持1.19.2

### ISSUE THREAD

**Issue by BeiGuaOvO** [SerendipityR-2022/EndMinecraftPlusV2#18]
能否尽快支持1.19.2？

**Comment by haha44444** [comment]
> 能否尽快支持1.19.2？

![image](https://user-images.githubusercontent.com/60396495/213531742-feb0d2cd-a199-42a4-8985-9c2ffe11be3f.png)
from [minecraft wiki](https://wiki.biligame.com/mc/Java%E7%89%881.19.2): "1.19.2是[Java版](https://wiki.biligame.com/mc/Java%E7%89%88)的一次次要更新，发布于2022年8月5日，修复了2个严重漏洞。此版本不兼容1.19的服务端，兼容1.19.1的服务端。"
就是说，使用1.19.1的客户端是可以进入1.19.2的服务端的

**Comment by BeiGuaOvO** [comment]
事实证明，1.19.1可以进入1.19.2
