### ISSUE TITLE
 Connection closed

### ISSUE THREAD

**Issue by snebftx** [SerendipityR-2022/EndMinecraftPlusV2#19]
我自己的mod服 1.16.5 这是需要配置什么吗 我把我的客户端mod都放在EndMinecraftPlusV2_Full目录下的mods文件夹内了
![Snipaste_2023-01-30_21-49-44](https://user-images.githubusercontent.com/39048335/215495235-42bad435-0420-47cb-bcfd-1b9c869b1be2.png)

**Comment by SerendipityR-2022** [comment]
暂不支持。
