### ISSUE TITLE
新增对1.19.3的支持

### ISSUE THREAD

**Issue by JinOuYongGu** [SerendipityR-2022/EndMinecraftPlusV2#21]
发现依赖MCP应该已经支持1.19.3了，所以希望作者能稍微更新一下

**Comment by StarryCamile** [comment]
还有1.18.1，与1.18.2并不互通

**Comment by SerendipityR-2022** [comment]
没有的版本，从仓库拉取项目，自行编译
https://github.com/GeyserMC/MCProtocolLib
