### ISSUE TITLE
增加崩溃方式

### ISSUE THREAD

**Issue by Radiation-pi** [SerendipityR-2022/EndMinecraftPlusV2#24]
目前的崩溃方式对于大多数服都没有用嘞，搞点新特性吧~
视频链接：https://www.youtube.com/watch?v=MIJR-nuwFi4
discord链接：https://discord.gg/moles

**Comment by SerendipityR-2022** [comment]
该模组核心代码如下，经测试在主流服务端中无效。
`this.client.player.networkHandler.sendPacket(new CreativeInventoryActionPacket(this.client.player.inventory.selectedSlot, 123344, 2957234, 2859623, ItemStack.EMPTY, new ItemStack(Items.DIAMOND, -1), duplicateItemsMap));
`
