### ISSUE TITLE
1.20.1  B站六芒猫

### ISSUE THREAD

**Issue by TuziXyz** [SerendipityR-2022/EndMinecraftPlusV2#31]
创建了一个1.20.1的服务器想这用这个测一下人数限制，因为我们团队的服务器需要好些优化才可以不容易卡，每次测试都需要把人叫进来就很不方便。有些人还没时间就叫不满100个。然后录视频又是100v6的一个素材，哎就没办法正常的测试

**Comment by SerendipityR-2022** [comment]
考虑这个项目
https://github.com/MCCTeam/Minecraft-Console-Client
