### ISSUE TITLE
大量日志

### ISSUE THREAD

**Issue by StarryCamile** [SerendipityR-2022/EndMinecraftPlusV2#33]
![图片](https://github.com/SerendipityR-2022/EndMinecraftPlusV2/assets/123795586/1784d009-71f4-4f94-92b6-88fef2b99092)
如图使用最新的EMPv2，MC版本1.19.4
理论上emp不支持这个版本的forge自动获取，但大量输出日志

**Comment by SerendipityR-2022** [comment]
已修复。
