### ISSUE TITLE
配置可能存在编码问题

### ISSUE THREAD

**Issue by YYTLZXD2327** [SerendipityR-2022/EndMinecraftPlusV2#34]
一直卡在这，文档是什么编码
![屏幕截图 2024-01-30 131811](https://github.com/SerendipityR-2022/EndMinecraftPlusV2/assets/143269826/4135dd3b-5cae-42fd-bca7-1131e6cd3339)

**Comment by StarryCamile** [comment]
![图片](https://github.com/SerendipityR-2022/EndMinecraftPlusV2/assets/123795586/1cbe47a0-9a17-468a-a7c7-1237acf1abcb)
长眼睛，让你输入y或者n

**Comment by YYTLZXD2327** [comment]
我输入了y还是出现

**Comment by StarryCamile** [comment]
> 我输入了y还是出现

回车了吗

**Comment by YYTLZXD2327** [comment]
回车了

**Comment by StarryCamile** [comment]
用记事本打开文件，点文件 另存为底下的编码改成utf8，如果不行改成ansi

**Comment by YYTLZXD2327** [comment]
ok了

**Comment by StarryCamile** [comment]
> ok了

close issue吧

**Comment by YYTLZXD2327** [comment]
什么东西
![屏幕截图 2024-01-30 133156](https://github.com/SerendipityR-2022/EndMinecraftPlusV2/assets/143269826/72dbba39-2017-498b-a33f-6cb573e69261)

**Comment by StarryCamile** [comment]
idk

**Comment by YYTLZXD2327** [comment]
Java17啊

**Comment by SerendipityR-2022** [comment]
在JDK1.8环境下运行
