### ISSUE TITLE
java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by RaindropV** [SerendipityR-2022/EndMinecraftPlusV2#38]
[ProtocolLib] 当前协议库版本: 47
[ProxyUtil] 正在获取代理...
[Internal Error] HTTP请求出错! 详细信息: java.net.SocketException: Connection reset
[ProxyUtil] 获取代理完成! (通过API获取 | 数量: 4599个)

我也不知道啥问题

**Comment by SerendipityR-2022** [comment]
代理API挂了，从配置文件中移除[www.66ip.cn]或者直接无视。
