### ISSUE TITLE
机器人在第一次加入的时候就显示被防火墙拦截

### ISSUE THREAD

**Issue by Bliod-Cook** [SerendipityR-2022/EndMinecraftPlusV2#4]
![2{BST6AZZOV9)0EU {1TDRQ](https://user-images.githubusercontent.com/108209631/186040073-146b86e0-65cb-447e-a1e0-9025f4d88f4c.png)
机器人在第一次加入的时候就显示被防火墙拦截

**Comment by Bliod-Cook** [comment]
https://user-images.githubusercontent.com/108209631/186041201-a0e024bf-e1e3-4ebf-ad3c-ee0b7abd1e40.mp4

视频如上

**Comment by SerendipityR-2022** [comment]
触发了BC端或子服的连接速率限制，与工具无关。
