### ISSUE TITLE
连接重置

### ISSUE THREAD

**Issue by xiaomuahua666** [SerendipityR-2022/EndMinecraftPlusV2#40]
![image](https://github.com/SerendipityR-2022/EndMinecraftPlusV2/assets/109423710/55ff72f8-19ed-438e-8561-c9f734bcf92f)
已使用java8运行程序
![image](https://github.com/SerendipityR-2022/EndMinecraftPlusV2/assets/109423710/f506d17c-b7ee-4100-9d1d-e25aef4b7b3d)
却提示连接重置(

**Comment by SerendipityR-2022** [comment]
存在一个或多个代理API无法访问，尝试编辑「config.yml」文件中的「Proxy.APIs」节点移除无效的代理API。

已收录到README常见问题部分。
